\chapter{Description of the Scottish Gaelic Interlinear Glossed Text Corpus}
\label{chap:Corpus}

	\begin{enumerate}
    \item Original goal of the corpus: a bank of examples of specific syntactic patterns for syntacticians.  
	\item Description of UA Celtic Group's Scottish Gaelic documentation project
    \item Collection of interlinear glossed text data used in syntax paper/dissertations AND language documentation
    \item Auto-glosser and literature on auto-glosser
	\end{enumerate}